---
title: Scientific writing notes
author: Haiyang Zhang
date: '2017-12-10'
slug: Useful-notes-about-writing
categories:
  - R
tags:
  - blogdown
summary: Useful-notes-about-writing
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
---

```{r include = FALSE}
knitr::opts_chunk$set(eval = FALSE, collapse = TRUE, comment = NA, tidy = FALSE)
```
Rewriting is the essence of writing. I pointed out the professional writers rewrite their sentences over and over and then rewrite what they have rewritten.                                --------William Zinsser


Clear thinking can emerge from clear writing!
Writing is not a post hoc work that after the work "getting the data".
It is the author's job to make the reader's job easy.
Most experienced writers get somethings down on a paper as fast as they can, just to have somethings to reviese.

  If one wants to succeed in sciences,  writing is the essential skills that one has to pass. Prof. [Elise Pendall](https://www.westernsydney.edu.au/hie/people/researchers/professor_elise_pendall) from Hawkesbury Institute for the Environment, Western Sydney University have organized a writing retreat November 2017. I have been lucky to join this retreat. It turned out to be a great experience. I here share some notes that I think are important. If you, as a scientist, have ever had a dream to become an artist, do write!


# Science Writing as storytelling and use SUCCES RULE to make the story sticky.
  **SUCCES RULE**
 1. *Simple* : simple idea capture the essence and core of an issue; it is not just "simplistic". a. Drawing a cartoon to explain complex. b. Re-focusing on your data and make it easier to follow. c. Buildding off established schemas.
 
 2. *Unexpected* : Incremental science can be important, but really good papers go beyond incremental to *novel*--they say somethings new and unexpected. Authors's job is find the novel point and highlight the unexpected elements. Frame new question and look for new insights. Make them clear in the writing. 
 
 3. *Concrete* : Ground and define your specific concepts either in widely understood schema or in the details that explain the abstractions.
 
 4. *Credible* : credibility come from concrete hypo, grounding ideas in previous work, discribing our methonds clearly, presenting data clearly and using appropriate statistics.
 
 5. *Emotional* : curiosity
 6. *Stories* : story structure-- (a) OCAR: openning, challenge, action and resolution. This rules should be work for the whole paper, sections, paragraph, or even individual sentences. (b) ABDCE:action, background, development, climax and ending. (c) LD: lead/development. (d) LDR: lead/development/resolution.
 
A good paper or proposal describle the larger problem and central characters (O); it frames an interesting question (C); it presents your research plan and results, developing the action (A); and it leaves the reader with an important conclusion about how our understanding of the world has changed (R). 
 
Good example for opening: *Is it clear what the paper is about?* Does it *frame the problem*? Does it introduce the *critical characters*? Like this one: "Since the late 1800s, N mineralization has been the *perceived* center point of the soil N cycle and the process that controls N availbility to plants." Bad example for opening: provide misdirection or no direction. "Well begun is half donw."

# The funnel: connecting Opening and Challenge

1. It is not very convincing to say "little is known about X". You must explicity define the problem. A concrete statement that defines a small knowledge gap will do better than a fuzzy one that fails to define one. Rather than say little is known, one could say, "the broad patterns are known, important details are not".
2. Offering a Solution before Defining a Problem
3. Literature review build the knowledge of wall while Introduction focus on the hole in that wall.Whenever you see that you’ve written a “Smith found . . .” sentence, ask whether the researcher, rather than the research, is what you want to tell us about. If not, rewrite it to focus on the fi ndings.
4. Bad example:“Although Smith (2003) reported X, Jones (2005) found Y.”
   Good one:While most reports suggest X (e.g., Smith, 2003), Jones (2005) found the opposite, arguing . . .”.   
   Another good one: When there are two camps with multiple papers supporting each side “There is still uncertainty about the nature of X, with some reports suggesting it is Y (Smith 2003) and others suggesting it is Z (Arif 2005).”
   
# The challenge

1."Our queston was" is better than "our objectives were".
2. keep in mind that I have a question that drove my work. Then Make the question clear!

# The Action

1. methods:the best way to describe a method is use a lead/development (LD) structure, providing an initial overview (you use this method for answer which question) for all and then the details for those who need them.

2. when there is a difference in mean value but statitics test are not significant: "Th e response in the treatment was 2.3 times higher than in the control,but the diff erence was only signifi cant at p = 0.07."

3. when the relationship between two variables have low R2 but sig. p:"the relationship between x and y is weak ( R2 = 0.10) but statistically significant ( p = 0.001)".


# resolution: take home message

1. Good resolution is straightforward, walking backword through the OCAR steps without distraction or complication. Give your resolution or contribution first, i.e. what you find. that is the deep meaning of these findings? How they benefit or advance our understanding or the challenge? Then, last step, go back further to the opening broad question.Restate the key conclution and implicationm and closes the circle via re-visit the opening problems.
2. Good resolution can also end with a concrete new question engages a reader’s curiosity and can be a powerful way to resolve a paper.

3. Bad resolution: weak (did not find sexy implication, didnot come back to general problem, did not offer new route to advance the current sciences), 
4. Bad resolution: Distracting (end with somehing from textbook that everybody know; always come back to the general topic of the science, do not go too far).
5.Bad resolution: undermine. "more research is needed to clarify our fi ndings.” is bad! Uncertainties remain. But the resolution is not the place to discuss them.Th ere are many ways to undermine your results, including expressions such as “but the importance of this has yet to be assessed,” “we hope that this review will simulate further research to answer the many unanswered questions,” “this topic deserves more research,” and so on. All of these use fuzzy expressions that suggest weaknesses in the existing work, rather than expressing substantive conclusions or pointing out clear new questions.


# OCAR structure the sentence 
In one sentence, openning is the topic and resolution will be stressed point.

1. Bad example:Net mineralization represents the nitrogen available to plants because it reflects the diff erence between microbial nitrogen release and uptake in soil.

Good example:“The amount of nitrogen available for plants is controlled by net mineralization — the diff erence between microbial nitrogen release and uptake in soil.”

Th is sentence says eff ectively the same thing, but it starts with an idea that most people understand — plants need nitrogen.


2. Bad example: "It has been predicted that the global average temperature will increase at a rate of 0.2˚C/decade."---------- stress predicted

Good example:"Global average temperature has been predicted to increase at a rate of 0.2˚C/decade.”". -------------------- stress temperature. Think clear about the topic.

3. Bad:The data did not support our initial hypothesis, as no clear trend in reaction rate with pH was observed.
   Good:The data did not support our initial hypothesis, as there was no clear trend in reaction rate with pH.
Sometimes the problem with a sentence is that there are words dangling aft er the real stress.画蛇添足，使得重点失效。

4. bad: The qualitative agreement between caribou’s preference for feeding on young leaves and the trend for protein to decline with leaf age supports the hypothesis that caribou migration is driven by the patterns of leaf-out and maturation spatially and temporally through their home range, rather than by weather.

a：what is the topic? how to open the sentence?
"Caribou prefer to feed n young leaves, rich in protein------"
b: what is the stress point? How to stress? "not by whether but by..."

Good: “Caribou prefer to feed on young, protein-rich leaves, supporting the hypothesis that migration is not driven by weather but by the spatial and temporal patterns of leaf-out and maturation.”

SUMMARY: 1. The topic should be short and clear.
2. The main verb should follow it immediately.
3. The key message should come at the stress.

5. long sentence: do not let reader wait the verb too long
Bad: “During the early part of the second millennium AD, from ~1050 – 1250 AD, a period corresponding to the timing of the MWP in many locales, albeit with a later onset than in some, lake level at Lake Tanganyika fell and remained relatively low.”

Good: At the beginning of the second millennium AD, lake level at Lake Tanganyika fell and remained relatively low during the period from ~1050 – 1250 AD, which corresponds to the timing of the MWP [Medieval Warm Period] in many locales, albeit with a later onset than in some areas.

# Flow
1.Th ere are two approaches to creating flow. The first is to write paragraphs where all the sentences are on the same team — dealing with a coherent theme and working together for a common goal. The second is to write sentences so the team forms a relay — each passes a baton at the transition, allowing an idea to flow cleanly from start to finish.







